# Write SQL queries to perform the following tasks using the Sakila database:

-- 1. List the number of films per category.
USE sakila;
SELECT category_id, COUNT(film_id) FROM film_category
GROUP BY category_id;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT store_id, city, country FROM store
INNER JOIN city
ON store.store_id = city.city_id
INNER JOIN country
ON city.city_id = country.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT store_id, SUM(amount) AS total_revenue_in_$ FROM payment
INNER JOIN store
ON payment.staff_id = store.store_id
GROUP BY store.store_id;

-- 4. Determine the average running time of films for each category.
SELECT AVG(length), category_id FROM film
JOIN film_category
ON film.film_id = film_category.film_id
GROUP BY category_id;

-- 5. Identify the film categories with the longest average running time.
SELECT category_id, AVG(length) AS long_duration FROM film
JOIN film_category
ON film.film_id = film_category.film_id
GROUP BY film_category.category_id
ORDER BY long_duration DESC;

-- 6. Display the top 10 most frequently rented movies in descending order.
SELECT film_id, title, rental_duration AS most_frequently_rented FROM film
ORDER BY most_frequently_rented DESC
LIMIT 10;

-- 7. Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT film.film_id, film.title, inventory.inventory_id, store.store_id FROM film
JOIN inventory 
ON film.film_id = inventory.inventory_id
JOIN store 
ON inventory.inventory_id = store.store_id
WHERE film.title = "Academy Dinosaur"
AND store.store_id = 1;

-- 8. Provide a list of all distinct film titles, along with their availability status in the inventory. 
-- Include a column indicating whether each title is 'Available' or 'NOT available.' 
-- Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."
SELECT 
	film.film_id, 
    film.title,  
CASE
	WHEN MAX(inventory.inventory_id) IS NULL THEN "NOT AVAILABLE"
    ELSE "AVAILABLE"
    END AS rental_availability
FROM film
LEFT JOIN inventory
ON film.film_id = inventory.film_id
GROUP BY film.film_id, film.title;


