# Write SQL queries to perform the following tasks using the Sakila database:

-- 1. List the number of films per category.
USE sakila;

SELECT c.name AS category_name, COUNT(fc.film_id) AS num_films
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
GROUP BY c.name;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT s.store_id, c.city, co.country
FROM store s
JOIN address a ON s.address_id = a.address_id
JOIN city c ON a.city_id = c.city_id
JOIN country co ON c.country_id = co.country_id;

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT s.store_id, SUM(p.amount) AS total_revenue_in_$ 
FROM store s
JOIN staff st ON s.store_id = st.staff_id
JOIN payment p ON st.staff_id = p.staff_id
GROUP BY s.store_id;

-- 4. Determine the average running time of films for each category.
SELECT AVG(length), category_id FROM film
JOIN film_category
ON film.film_id = film_category.film_id
GROUP BY category_id;

-- 5. Identify the film categories with the longest average running time.
SELECT category_id, AVG(length) AS long_duration FROM film
JOIN film_category
ON film.film_id = film_category.film_id
GROUP BY film_category.category_id
ORDER BY long_duration DESC;

-- 6. Display the top 10 most frequently rented movies in descending order.
SELECT film_id, title, rental_duration AS most_frequently_rented FROM film
ORDER BY most_frequently_rented DESC
LIMIT 10;

-- 7. Determine if "Academy Dinosaur" can be rented from Store 1.
SELECT film.film_id, film.title, inventory.inventory_id, store.store_id FROM film
JOIN inventory 
ON film.film_id = film.film_id
JOIN store 
ON store.store_id = store.store_id
WHERE film.title = "Academy Dinosaur"
AND store.store_id = 1;

-- 8. Provide a list of all distinct film titles, along with their availability status in the inventory. 
-- Include a column indicating whether each title is 'Available' or 'NOT available.' 
-- Note that there are 42 titles that are not in the inventory, and this information can be obtained using a CASE statement combined with IFNULL."
SELECT 
	film.film_id, 
    film.title,  
CASE
	WHEN MAX(inventory.inventory_id) IS NULL THEN "NOT AVAILABLE"
    ELSE "AVAILABLE"
    END AS rental_availability
FROM film
LEFT JOIN inventory
ON film.film_id = inventory.film_id
GROUP BY film.film_id, film.title;


